Removed some old ava stuff
kentcdodds/react-jest-workshop pull request #3
Opened 2016-10-28 14:32 UTC by im-martijn

- Instructions was the old one from the ava workshop
- Removed old line refering to nyc in .gitignore

2016-10-28 15:41 UTC, kentcdodds requested changes

2016-10-28 15:41 UTC, kentcdodds commented on .gitignore
> -.nyc_output/
This is great :)

2016-10-28 15:41 UTC, kentcdodds commented on INSTRUCTIONS.md
> -# If you wanna help, that'd be great
Note this. I'd actually rather keep things around as a reference for when I finally do update the instructions. If you want to do that, be my guest! :D

2016-10-31 15:50 UTC, im-martijn commented on INSTRUCTIONS.md
> -# If you wanna help, that'd be great
I'm not sure I'd be able to. Not much experience with either Jest or Ava. That's why I was looking at this repo. ;)

2016-10-31 15:58 UTC, kentcdodds commented on INSTRUCTIONS.md
> -# If you wanna help, that'd be great
That's fine. Thanks anyway.

2016-10-31 16:01 UTC, im-martijn commented
I restored INSTRUCTIONS.md.

2016-10-31 16:06 UTC, kentcdodds commented
Make sure that you force push that change. The PR still shows the instructions removed.

2016-11-07 15:13 UTC, im-martijn commented
Are you sure? I see the [commit from October 31st](https://github.com/kentcdodds/react-jest-workshop/pull/3/commits/a1d14b6cfbd00cdd55d417672209b0fc8fafe5fd), which adds back the INSTRUCTIONS.md. Or am I wrong?

2016-11-07 19:55 UTC, kentcdodds commented
Whoops, you're correct! Thank you!

2016-11-07 19:55 UTC, merged